# Generated by Django 4.1 on 2023-04-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user_customuser_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_document',
            field=models.ImageField(null=True, upload_to='media/user/registration'),
        ),
    ]
