# Generated by Django 4.1 on 2024-02-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_inspectortype'),
        ('account', '0038_customuser_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHaveInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepali_name', models.CharField(max_length=200)),
                ('government_id', models.CharField(max_length=300)),
                ('government_issued_document', models.FileField(upload_to='media/user/inspector')),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.branches')),
                ('inspector_type', models.ManyToManyField(null=True, to='offices.inspectortype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
