# Generated by Django 4.1 on 2024-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhaveinspector',
            name='government_issued_document',
            field=models.FileField(blank=True, null=True, upload_to='media/user/inspector'),
        ),
    ]
