# Generated by Django 4.1 on 2024-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_userhaveinspector_government_issued_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='test_type',
            field=models.ManyToManyField(default=None, related_name='users', to='account.testtype'),
        ),
    ]
