# Generated by Django 4.1 on 2024-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_inspectortype'),
        ('account', '0042_alter_customuser_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhaveinspector',
            name='inspector_type',
            field=models.ManyToManyField(to='offices.inspectortype'),
        ),
    ]
