# Generated by Django 4.1 on 2024-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_userhaveinspector_inspector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public_analyst',
            field=models.BooleanField(default=False),
        ),
    ]
