# Generated by Django 4.1 on 2023-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255)),
                ('reg_document', models.FileField(upload_to='')),
                ('user_renew_document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=255)),
                ('ref_test_method', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('results', models.CharField(max_length=255)),
                ('mandatory_standard', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('mfd', models.DateField()),
                ('dfb', models.DateField()),
                ('batch', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('report_date', models.DateField()),
                ('amendments', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('note', models.TextField()),
            ],
        ),
    ]
