# Generated by Django 4.1 on 2023-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_sampleform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='name',
            field=models.IntegerField(null=True),
        ),
    ]
