# Generated by Django 4.1 on 2023-05-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_sampleformparameterformulacalculate_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='supervisor_user',
        ),
    ]
