# Generated by Django 4.1 on 2023-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_sampleformhasparameter_supervisor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='ammount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='payment_receipt',
            field=models.FileField(null=True, upload_to='uploads/receipt'),
        ),
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='register_date',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
