# Generated by Django 4.1 on 2023-05-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_sampleform_supervisor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='input_fields_value',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='result',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='sample_form',
        ),
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='updated_date',
        ),
    ]
