# Generated by Django 4.1 on 2023-04-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_clientcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcategory',
            name='user',
        ),
    ]
