# Generated by Django 4.1 on 2023-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_sampleform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
