# Generated by Django 4.1 on 2023-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_clientcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcategory',
            name='reg_document',
            field=models.ImageField(null=True, upload_to='media/client_category'),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='user_renew_document',
            field=models.ImageField(null=True, upload_to='media/client_category'),
        ),
    ]
