# Generated by Django 4.1 on 2023-05-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_sampleformhasparameter_ammount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='payment_receipt',
        ),
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='voucher_number',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=100, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=155, null=True)),
                ('register_date', models.CharField(blank=True, max_length=155, null=True)),
                ('ammount', models.IntegerField(blank=True, null=True)),
                ('payment_receipt', models.FileField(null=True, upload_to='uploads/receipt')),
                ('sample_form', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='management.sampleform')),
            ],
        ),
    ]
