# Generated by Django 4.1 on 2023-04-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_clientcategory_reg_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcategory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientcategory',
            name='reg_document',
        ),
        migrations.RemoveField(
            model_name='clientcategory',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='clientcategory',
            name='user_renew_document',
        ),
    ]
