# Generated by Django 4.1 on 2023-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_sampleform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.IntegerField(null=True)),
                ('parameter', models.CharField(max_length=255)),
                ('ref_test_method', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=100)),
                ('results', models.CharField(max_length=100)),
                ('mandatory_standard', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='results',
        ),
        migrations.AddField(
            model_name='commodity',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='commodity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='parameter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
