# Generated by Django 4.1 on 2023-05-15 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_remove_sampleformhasparameter_ammount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='supervisor_user',
        ),
        migrations.AddField(
            model_name='sampleform',
            name='supervisor_user',
            field=models.ManyToManyField(related_name='sample_has_parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
