# Generated by Django 4.1 on 2023-05-15 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_remove_sampleformhasparameter_supervisor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='supervisor_user',
            field=models.ManyToManyField(null=True, related_name='sample_has_parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
