# Generated by Django 4.1 on 2023-05-15 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_alter_sampleform_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='supervisor_user',
            field=models.ManyToManyField(default=None, related_name='sample_has_parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
