# Generated by Django 4.1 on 2023-05-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_sampleform_supervisor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleformhasparameter',
            old_name='Commodity',
            new_name='commodity',
        ),
    ]
