# Generated by Django 4.1 on 2023-05-16 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_payment_created_date_payment_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFormParameterFormulaCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.commodity')),
                ('parameter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.testresult')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='management.sampleform')),
            ],
        ),
    ]
