# Generated by Django 4.1 on 2023-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_auto_calculate_result_sampleformparameterformulacalculate_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='input_fields_value',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='result',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
