# Generated by Django 4.1 on 2023-05-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_sampleformparameterformulacalculate_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.commodity'),
        ),
    ]
