# Generated by Django 4.1 on 2023-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_sampleformparameterformulacalculate_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='input_fields_value',
            field=models.JSONField(max_length=2000, null=True),
        ),
    ]
