# Generated by Django 4.1 on 2023-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_sampleformparameterformulacalculate_input_fields_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='input_fields_value',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
