# Generated by Django 4.1 on 2024-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0184_alter_approvedlist_user_alter_verifiedlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='is_print',
            field=models.BooleanField(default=False),
        ),
    ]
