# Generated by Django 4.1 on 2024-02-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_inspectortype'),
        ('management', '0185_sampleform_is_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFormHaveInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_serial_number', models.CharField(max_length=150)),
                ('letter_number', models.CharField(max_length=150)),
                ('letter_submitted_date', models.CharField(max_length=150)),
                ('sample_collected_date', models.CharField(max_length=150)),
                ('sample_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to='management.sampleform')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_form', to='offices.inspectortype')),
            ],
        ),
    ]
