# Generated by Django 4.1 on 2024-02-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0186_sampleformhaveinspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='remarks_recheck_verifier',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='remarks_reject_verifier',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='supervisor_user',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='verifier_remarks',
        ),
    ]
