# Generated by Django 4.1 on 2024-02-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0189_remove_testresult_results_historicaltestresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsampleform',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='language',
        ),
    ]
