# Generated by Django 4.1 on 2024-02-23 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0190_remove_historicalsampleform_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsampleform',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='owner_user',
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='owner_user_obj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_have_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
