# Generated by Django 4.1 on 2024-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0191_remove_historicalsampleform_owner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='feed_owner_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='preservatives_details_and_quantity',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='sample_collected_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
