# Generated by Django 4.1 on 2024-02-23 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0194_alter_sampleformhaveinspector_feed_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsampleform',
            name='owner_user_obj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='owner_user_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_have_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
