# Generated by Django 4.1 on 2024-02-25 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0195_alter_historicalsampleform_owner_user_obj_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisorsampleform',
            unique_together={('sample_form', 'supervisor_user')},
        ),
    ]
