# Generated by Django 4.1 on 2024-02-25 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0195_alter_historicalsampleform_owner_user_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='sample_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_has_parameter_analyst', to='management.sampleform'),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='super_visor_sample_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_has_parameter_analyst', to='management.supervisorsampleform'),
        ),
        migrations.AlterField(
            model_name='supervisorsampleform',
            name='sample_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_sample_form', to='management.sampleform'),
        ),
        migrations.AlterField(
            model_name='supervisorsampleform',
            name='supervisor_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
