# Generated by Django 4.1 on 2024-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0196_alter_sampleformhasparameter_sample_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsampleformhasparameter',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsampleformparameterformulacalculate',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsampleformverifier',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupervisorsampleform',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sampleformparameterformulacalculate',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sampleformverifier',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsampleform',
            name='performance_remarks',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=20, null=True),
        ),
    ]
