# Generated by Django 4.1 on 2024-03-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0196_alter_sampleformhasparameter_sample_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='sample_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_has_parameter_analyst', to='management.sampleform'),
        ),
    ]
