# Generated by Django 4.1 on 2024-03-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0197_historicalsampleformhasparameter_performance_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsampleform',
            name='form_available',
            field=models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user'), ('verifier', 'verifier'), ('admin', 'ADMIN')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='form_available',
            field=models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user'), ('verifier', 'verifier'), ('admin', 'ADMIN')], max_length=100, null=True),
        ),
    ]
