# Generated by Django 4.1 on 2024-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0198_alter_historicalsampleform_form_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsampleformhasparameter',
            name='form_available',
        ),
        migrations.RemoveField(
            model_name='sampleformhasparameter',
            name='form_available',
        ),
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='sample_received_date',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='smu_sample_condition',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='sampleformhaveinspector',
            name='supervisor_sample_condition',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
    ]
