# Generated by Django 4.1 on 2024-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0199_remove_historicalsampleformhasparameter_form_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsampleform',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
    ]
