# Generated by Django 4.1 on 2024-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0200_historicalsampleform_is_back_sampleform_is_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsampleform',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='historicalsampleform',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='historicalsampleformverifier',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='historicalsampleformverifier',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsampleformverifier',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupervisorsampleform',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupervisorsampleform',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsupervisorsampleform',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='sampleformverifier',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='sampleformverifier',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleformverifier',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsampleform',
            name='back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='supervisorsampleform',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisorsampleform',
            name='submit_back_remarks',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
