# Generated by Django 4.1 on 2024-03-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0201_historicalsampleform_back_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsampleformverifier',
            name='back_remarks',
        ),
        migrations.RemoveField(
            model_name='historicalsampleformverifier',
            name='is_back',
        ),
        migrations.RemoveField(
            model_name='historicalsampleformverifier',
            name='submit_back_remarks',
        ),
        migrations.RemoveField(
            model_name='historicalsupervisorsampleform',
            name='back_remarks',
        ),
        migrations.RemoveField(
            model_name='historicalsupervisorsampleform',
            name='is_back',
        ),
        migrations.RemoveField(
            model_name='historicalsupervisorsampleform',
            name='submit_back_remarks',
        ),
        migrations.RemoveField(
            model_name='sampleformverifier',
            name='back_remarks',
        ),
        migrations.RemoveField(
            model_name='sampleformverifier',
            name='is_back',
        ),
        migrations.RemoveField(
            model_name='sampleformverifier',
            name='submit_back_remarks',
        ),
        migrations.RemoveField(
            model_name='supervisorsampleform',
            name='back_remarks',
        ),
        migrations.RemoveField(
            model_name='supervisorsampleform',
            name='is_back',
        ),
        migrations.RemoveField(
            model_name='supervisorsampleform',
            name='submit_back_remarks',
        ),
        migrations.AlterField(
            model_name='historicalsampleform',
            name='is_back',
            field=models.CharField(choices=[('smu_back', 'Smu Back'), ('supervisor_back', 'Supervisor Back'), ('verifier_back', 'Verifier Back'), ('', '')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='is_back',
            field=models.CharField(choices=[('smu_back', 'Smu Back'), ('supervisor_back', 'Supervisor Back'), ('verifier_back', 'Verifier Back'), ('', '')], max_length=30, null=True),
        ),
    ]
