# Generated by Django 4.1 on 2024-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0202_remove_historicalsampleformverifier_back_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsampleform',
            name='is_back_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='is_back_submit',
            field=models.BooleanField(default=False),
        ),
    ]
