# Generated by Django 4.1 on 2024-03-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0203_historicalsampleform_is_back_submit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsampleform',
            name='smu',
            field=models.ForeignKey(blank=True, db_constraint=False, default=71, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='smu',
            field=models.ForeignKey(default=71, on_delete=django.db.models.deletion.PROTECT, related_name='smu_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
