# Generated by Django 4.1 on 2024-03-25 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0205_alter_historicalsampleform_smu_alter_sampleform_smu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='smu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smu_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
