# Generated by Django 4.1 on 2024-03-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0200_historicalsampleform_is_back_sampleform_is_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_available', models.PositiveSmallIntegerField(choices=[(1, 'SUPERADMIN'), (2, 'SMU'), (3, 'SUPERVISOR'), (4, 'ANALYST'), (5, 'USER'), (6, 'VERIFIER'), (7, 'ADMIN'), (8, 'INSPECTOR')])),
                ('track_types', models.CharField(choices=[('new_sample_form', 'Sample Request'), ('recheck_sample', 'Recheck Sample'), ('reject', 'Reject'), ('assigned_supervisor', 'Assigned Supervisor'), ('re_assigned_superviso', 'Re-assigned Supervisor'), ('assigned_analyst', 'Assigned Analyst'), ('parameter_recheck', 'Recheck Parameter'), ('re_assigned_parameter', 'Re-assigned Parameter'), ('sent_to_supervisor', 'Sent to Supervisor'), ('assigned_verifier', 'Assigned Verifier'), ('assigned_admin', 'Assigned Admin'), ('approved_sample_form', 'Approved Sample Form')], max_length=33)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('not_assigned', 'not_assigned'), ('not_verified', 'not_verified'), ('not_approved', 'not_approved'), ('verified', 'verified'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected'), ('Test Completed', 'Test Completed'), ('parameter_recheck', 'Parameter Recheck'), ('back', 'back')], max_length=30)),
                ('form_available_string', models.CharField(choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user'), ('verifier', 'verifier'), ('admin', 'ADMIN')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('from_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_back', to=settings.AUTH_USER_MODEL)),
                ('sample_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_sample', to='management.sampleform')),
                ('to_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_backs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sample', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
