# Generated by Django 4.1 on 2024-03-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletrack',
            name='from_back',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampletrack',
            name='to_back',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_backs', to=settings.AUTH_USER_MODEL),
        ),
    ]
