# Generated by Django 4.1 on 2024-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0002_alter_sampletrack_from_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletrack',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('not_assigned', 'not_assigned'), ('not_verified', 'not_verified'), ('not_approved', 'not_approved'), ('verified', 'verified'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected'), ('Test Completed', 'Test Completed'), ('parameter_recheck', 'Parameter Recheck'), ('back', 'back'), ('submit_back', 'Submit Back')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sampletrack',
            name='to_back',
            field=models.CharField(choices=[('smu', 'SMU'), ('supervisor', 'SUPERVISOR'), ('verifier', 'VERIFIER'), ('', '')], default='', max_length=20),
        ),
    ]
