# Generated by Django 4.1 on 2024-03-15 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backtrack', '0003_alter_sampletrack_status_alter_sampletrack_to_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletrack',
            name='from_back',
        ),
        migrations.RemoveField(
            model_name='sampletrack',
            name='track_types',
        ),
        migrations.AddField(
            model_name='sampletrack',
            name='to_back_str',
            field=models.CharField(choices=[('smu', 'SMU'), ('supervisor', 'SUPERVISOR'), ('verifier', 'VERIFIER'), ('', '')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sampletrack',
            name='to_back',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_backs', to=settings.AUTH_USER_MODEL),
        ),
    ]
