# Generated by Django 4.1 on 2024-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0004_remove_sampletrack_from_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletrack',
            name='form_available_string',
        ),
        migrations.AlterField(
            model_name='sampletrack',
            name='form_available',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user'), ('verifier', 'verifier'), ('admin', 'ADMIN')], max_length=20),
        ),
    ]
