# Generated by Django 4.1 on 2024-03-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0005_remove_sampletrack_form_available_string_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletrack',
            name='to_back_str',
        ),
    ]
