# Generated by Django 4.1 on 2024-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0006_remove_sampletrack_to_back_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletrack',
            name='remarks',
            field=models.CharField(max_length=4000),
        ),
    ]
