# Generated by Django 4.1 on 2024-02-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('notification_type', models.CharField(default='push', max_length=200, null=True)),
                ('notification_message', models.CharField(max_length=200, null=True)),
                ('particular_message', models.TextField(null=True)),
                ('path', models.CharField(max_length=1000, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('group_notification', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('to_notification', models.ManyToManyField(related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
