# Generated by Django 4.1 on 2024-03-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='method_type',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
