# Generated by Django 4.1 on 2024-03-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_notification_method_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
