# Generated by Django 4.1 on 2024-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', 'Food'), ('feed', 'Feed')], default=None, max_length=155, null=True)),
            ],
        ),
    ]
