# Generated by Django 4.1 on 2024-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_inspectortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='nepali_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
