# Generated by Django 4.1 on 2024-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_branches_nepali_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectortype',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('feed', 'Feed')], max_length=155),
        ),
    ]
